configs:
  plugins:
    - &aws-sm
      seek-oss/aws-sm#v2.3.0:
        env:
          NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token
    - &docker-compose
      docker-compose#v5.12.1:
        environment:
          - GITHUB_API_TOKEN
        propagate-environment: true
        run: app
    - &docker
      docker#v5.10.0:
